---
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Deploy telegraf
  hosts: "all"
  gather_facts: true
  user: root
  tasks:
    - name: Install ipaddr python module for MaaS
      apt:
        pkg: "python-ipaddr"
        state: "latest"
    - name: Add influxdata apt-keys
      apt_key:
        url: "https://repos.influxdata.com/influxdb.key"
        state: "present"
    - name: Add influxdata repo
      apt_repository:
        repo: "deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: "present"
        update_cache: yes
    - name: Install telegraf
      apt:
        pkg: "telegraf"
        state: "latest"
    - name: Install Ethtool
      apt:
        pkg: "ethtool"
        state: "latest"
    - name: Create telegraf plugin dir
      file:
        path: "/opt/telegraf"
        state: directory
        mode: "0755"
    - name: Drop telegraf plugin file(s)
      copy:
        src: "files/{{ item.value.plugin_name }}"
        dest: "/opt/telegraf/{{ item.value.plugin_name }}"
        mode: '0755'
      with_dict: "{{ command_plugins }}"
      when:
        - item.value.when_group | bool
        - inventory_hostname in groups[item.value.group]
    - name: Add to command plugins
      set_fact:
        commands: "{{ commands | union(item.value.command) }}"
      with_dict: "{{ command_plugins }}"
      when:
        - item.value.when_group | bool
        - inventory_hostname in groups[item.value.group]
      tags:
        - always
    - name: Copy JSON to Influx parser
      copy:
        src: "files/jsontoinflux.py"
        dest: "/opt/telegraf/jsontoinflux.py"
    - name: Drop telegraf config file
      template:
        src: templates/telegraf.conf.j2
        dest: /etc/telegraf/telegraf.conf
      register: telegraf_config
    - name: copy the openrc file to home directory
      shell: cp /root/openrc /home/openrc;chmod 644 /home/openrc
      when: inventory_hostname in groups['utility_all']
    - name: copy the openrc file for MaaS
      shell: cp /root/openrc /home/openrc-maas;chmod 644 /home/openrc-maas
      when: inventory_hostname in groups['utility_all']
    - name: copy the openrc_monitoring file
      copy:
        src: "files/openrc_monitoring"
        dest: "/home/openrc_monitoring"
    - name: Clone rpc-openstack MaaS
      git: repo=https://github.com/osic/reliability-rpc-openstack.git
           dest=/opt/rpc-openstack
           accept_hostkey=yes
           force=yes
           recursive=no
      when: inventory_hostname in groups['utility_all']|union(groups['rabbitmq_all'])
    - name: Enable Monitoring User in RabbitMQ
      shell: "rabbitmqctl change_password monitoring {{ rabbitmq_monitoring_password }};rabbitmqctl set_user_tags monitoring monitoring"
      when: inventory_hostname in groups['rabbitmq_all']
    - name: Add rabbitmq monitoring password to openrc_monitoring
      shell: "echo \"export rabbitmq_monitoring_pwd={{ rabbitmq_monitoring_password }}\" >> /home/openrc_monitoring"
      when: inventory_hostname in groups['rabbitmq_all']
    - name: Enable and restart telegraf
      service:
        name: "telegraf"
        enabled: true
        state: restarted
      when: telegraf_config | changed
    - name: Enable and start telegraf
      service:
        name: "telegraf"
        enabled: true
        state: started
      when: not telegraf_config | changed
  vars:
    commands : []
    command_plugins:
      keystone_api:
        plugin_name: "maas_output_parser.py"
        command:
          - "python /opt/telegraf/maas_output_parser.py keystone_api /opt/rpc-openstack/maas/plugins/keystone_api_local_check.py"
        group: "utility_all"
        when_group: "{{ (groups['utility_all'] | length) > 0 }}"
      neutron_api:
        plugin_name: "maas_output_parser.py"
        command:
          - "python /opt/telegraf/maas_output_parser.py neutron_api /opt/rpc-openstack/maas/plugins/neutron_api_local_check.py"
        group: "utility_all"
        when_group: "{{ (groups['utility_all'] | length) > 0 }}"
      nova_api:
        plugin_name: "maas_output_parser.py"
        command:
          - "python /opt/telegraf/maas_output_parser.py nova_api /opt/rpc-openstack/maas/plugins/nova_api_local_check.py"
        group: "utility_all"
        when_group: "{{ (groups['utility_all'] | length) > 0 }}"
      glance_api:
        plugin_name: "maas_output_parser.py"
        command:
          - "python /opt/telegraf/maas_output_parser.py glance_api /opt/rpc-openstack/maas/plugins/glance_api_local_check.py"
        group: "utility_all"
        when_group: "{{ (groups['utility_all'] | length) > 0 }}"
      cinder_api:
        plugin_name: "maas_output_parser.py"
        command:
          - "python /opt/telegraf/maas_output_parser.py cinder_api \"/opt/rpc-openstack/maas/plugins/cinder_api_local_check.py $cinder_api\""
        group: "utility_all"
        when_group: "{{ (groups['utility_all'] | length) > 0 }}"
      cinder:
        plugin_name: "cinder_data.py"
        command:
          - "python /opt/telegraf/cinder_data.py"
        group: "utility_all"
        when_group: "{{ (groups['cinder_all'] | length) > 0 }}"
      kvm:
        plugin_name: "kvm_virsh.py"
        command:
          - "python /opt/telegraf/kvm_virsh.py"
        group: "nova_compute"
        when_group: "{{ (groups['nova_compute'] | length) > 0 }}"
      interface_max_speed:
        plugin_name: "maxspeed_interface.py"
        command:
          - "python /opt/telegraf/maxspeed_interface.py"
        group: "all"
        when_group: "{{ (groups['all'] | length) > 0 }}"
      rabbitmq:
        plugin_name: "maas_output_parser.py"
        command:
          - "python /opt/telegraf/maas_output_parser.py rabbitmq \"/opt/rpc-openstack/maas/plugins/rabbitmq_status.py -H $rabbitmq -U monitoring -p $rabbitmq_monitoring_pwd\""
        group: "rabbitmq_all"
        when_group: "{{ (groups['rabbitmq_all'] | length) > 0 }}"
      nova_service:
        plugin_name: "maas_output_parser.py"
        command:
          - "python /opt/telegraf/maas_output_parser.py nova_service \"/opt/rpc-openstack/maas/plugins/nova_service_check.py $nova_api_os_compute\""
        group: "utility_all"
        when_group: "{{ (groups['utility_all'] | length) > 0 }}"
      neutron_service:
        plugin_name: "maas_output_parser.py"
        command:
          - "python /opt/telegraf/maas_output_parser.py neutron_service \"/opt/rpc-openstack/maas/plugins/neutron_service_check.py $neutron_server\""
        group: "utility_all"
        when_group: "{{ (groups['utility_all'] | length) > 0 }}"
  vars_files:
    - vars.yml